export const MODAL_ADD_ACTIVITY = 'MODAL_ADD_ACTIVITY';
export const MODAL_EDIT_ACTIVITY = 'MODAL_EDIT_ACTIVITY';
export const MODAL_ADD_TASK = 'MODAL_ADD_TASK';
export const MODAL_EDIT_TASK = 'MODAL_EDIT_TASK';
export const MODAL_ADD_SCHEDULE = 'MODAL_ADD_SCHEDULE';
export const MODAL_EDIT_SCHEDULE = 'MODAL_EDIT_SCHEDULE';
export const MODAL_ADD_CATEGORY = 'MODAL_ADD_CATEGORY';
